-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgG7k/HUS/Q7IlAPIP
YIC0Ej/8IfEGKF4alZGSYe+TJr6gCgYIKoZIzj0DAQehRANCAATknJogkkgRXJJu
c3u7T3OPk67YZR/tOA5QoFUfwiRQWhGSpbM0w9a/Q/B5vIKAdZa8cjruamAtbeyI
e0RUxq6t
-----END PRIVATE KEY-----